### ISSUE TITLE
How

### ISSUE THREAD

**Issue by VanZPro** [dkmpostor/node-stumble-guys#1]
Gimana carinya
http://kitkabackend.eastus.cloudapp.azure.com:5010/round/finishv2/3
Di Http canary ga bisa padahal gua udah win 1× di stumble guys nya

**Comment by dkmpostor** [comment]
Cek readme

**Comment by Satuhu** [comment]
Abis win, claim dulu trus lgsg ke apknya, copy auth nya,  lalu run aja
