### ISSUE TITLE
help

### ISSUE THREAD

**Issue by IqbalHahaha** [dkmpostor/node-stumble-guys#6]
![Screenshot_2022-06-16-10-34-23-55](https://user-images.githubusercontent.com/107595211/173979023-ec42f6fe-fdec-4dc2-91d3-5241d479507c.jpg)

ini gimana ya bang?

**Comment by dkmpostor** [comment]
dir dlu bg
bner ga direktorinya

**Comment by arshizx** [comment]
lu download termuxnya dimana? kalau di playstore itu versi lama kalau gw sih download disini https://f-droid.org/repo/com.termux_118.apk langsung bisa
