### ISSUE TITLE
aut nya gk ada

### ISSUE THREAD

**Issue by UNTAAA** [dkmpostor/node-stumble-guys#9]
Bro gua udh win sekali.. terus kan claim tuh...
Gua buka http canary gua cari http://kitkabackend.eastus.cloudapp.azure.com:5010/round/finishv2/3 di http canary nya gk ada ya bro giamna ya

Itu http canary nya musti install ca root certificate gk?

**Comment by dkmpostor** [comment]
Perlu bg Root certificatenya , jgn di skip

**Comment by UNTAAA** [comment]
> 

Lu pake di android berapa bro.. soalnya gua di A11 beda cara install ca certificate nya.
Device gua juga udh di root

**Comment by dkmpostor** [comment]
Android 10 ane ,, cari yutub bnyk install cert http canary android 11/12

**Comment by UNTAAA** [comment]
Bro gua udh instal ca certificate...
Gua coba login gk bisa..
![IMG_20220618_053505](https://user-images.githubusercontent.com/107556643/174409239-746f53ba-4f99-4e4d-8e6d-45bbc2eebf2c.jpg)
